apiVersion: skaffold/v4beta6
kind: Config

build:
  artifacts:
    - image: mahmoudyahia/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mahmoudyahia/client-ticketing
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: mahmoudyahia/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .

deploy:
  kubectl: {}

manifests:
  rawYaml:
    - ./infra/k8s/*
