apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: mahmoudyahia/auth
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef: 
              name: jwt-secret
              key: JWT_KEY
        ports:
        - containerPort: 80

#kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - name: auth-port
    protocol: TCP
    port: 3000
    targetPort: 3000
