apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mahmoudyahia/client-ticketing
          env:
            - name: ReCAPTCHA_SITEKEY
              value: 6LfGwe8oAAAAAFchFocTLNB_kjnxo0QJ0OBHK4Jl
            - name: NEXT_PUBLIC_PAYPAL_CLIENT_ID
              value: ATQD5CcRw9GXtLi2jtK6zyV6UltUTGvXFXcl82JvhJCmv-pIp5YvwwRsJ30vzEC5IUPDCyLYLRrPT1MB
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client-port
      protocol: TCP
      port: 3000
      targetPort: 3000
