apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
  labels:
    app: expiration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: mahmoudyahia/expiration
          env:
            - name: NATS_ClIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_URL
              value: 'https://nats-srv:4222'
            - name: REDIS_HOST
              value: expiration-redis-srv
          ports:
            - containerPort: 80


